LANGUAGES = {
    "en": {
        "app_title": "WMR Group Apps",
        "welcome_title": "WMR GROUP APPLICATION MANAGER",
        "welcome_text": "APPLICATION DISTRIBUTION AND MANAGEMENT SYSTEM\n\nFEATURES:\n• Automatic update checking via GitHub API\n• EXE/BAT file detection in installed applications\n• Centralized application management\n• Version control and update notifications\n• Easy installation and removal\n\nSELECT AN APPLICATION FROM THE LEFT PANEL TO VIEW DETAILS\nAND MANAGE INSTALLATION.",
        "available_apps": "AVAILABLE APPLICATIONS",
        "category_filter": "CATEGORY FILTER:",
        "all": "ALL",
        "flashing_tools": "FLASHING TOOLS",
        "utilities": "UTILITIES",
        "installed": "INSTALLED",
        "not_installed": "NOT INSTALLED",
        "check_updates": "CHECK UPDATES",
        "open_install_folder": "OPEN INSTALL FOLDER",
        "open_install_directory": "OPEN INSTALL DIRECTORY",
        "check_for_updates": "CHECK FOR UPDATES",
        "github": "GITHUB",
        "update_to": "UPDATE TO",
        "uninstall": "UNINSTALL",
        "detect_files": "DETECT FILES",
        "detect_all_files": "DETECT ALL EXECUTABLES",
        "install": "INSTALL",
        "author": "AUTHOR",
        "release_date": "RELEASE DATE",
        "github_stars": "GITHUB STARS",
        "category": "CATEGORY",
        "install_path": "INSTALL PATH",
        "status": "STATUS",
        "local_version": "LOCAL VERSION",
        "update_available": "UPDATE AVAILABLE",
        "detected_executable_files": "DETECTED EXECUTABLE FILES",
        "no_files_detected": "NO EXECUTABLE FILES DETECTED\n\nClick 'DETECT FILES' to scan the installation folder",
        "run": "RUN",
        "run_menu": "RUN MENU",
        "open_folder": "OPEN FOLDER",
        "installing": "INSTALLING",
        "preparing_download": "PREPARING DOWNLOAD...",
        "downloading_from_github": "DOWNLOADING FROM GITHUB...",
        "extracting_files": "EXTRACTING FILES...",
        "copying_files": "COPYING FILES...",
        "creating_launchers": "CREATING LAUNCHERS...",
        "finalizing": "FINALIZING...",
        "installation_complete": "INSTALLATION COMPLETE!",
        "installation_failed": "INSTALLATION FAILED!",
        "view_error_details": "VIEW ERROR DETAILS",
        "installation_error": "INSTALLATION ERROR",
        "close": "CLOSE",
        "select_language": "Select Language",
        "english": "English",
        "russian": "Russian",
        "continue": "Continue",
        "updating": "UPDATING",
        "update_available_title": "Update Available",
        "update_available_text": "New version {version} is available. Update now?",
        "updating_app": "Updating application...",
        "update_complete": "Update complete!",
        "no_update": "No update available",
        "error": "Error",
        "success": "Success",
        "info": "Information",
        "warning": "Warning",
        "yes": "YES",
        "no": "NO",
        "about": "ABOUT",
        "about_program": "ABOUT PROGRAM",
        "program_name": "WMR Group Apps",
        "version": "Version",
        "developer": "Developer",
        "github_repo": "GitHub Repository",
        "description": "Application distribution and management system for WMR Group projects",
        "features": "Features",
        "feature1": "• GitHub integration and automatic updates",
        "feature2": "• Multi-platform support (Windows, Linux, macOS)",
        "feature3": "• Multi-language interface (English, Russian)",
        "feature4": "• Centralized application management",
        "feature5": "• Executable file detection and management",
        "license": "License",
        "mit_license": "MIT License",
        "loading": "Loading...",
        "please_wait": "Please wait",
        "sync": "SYNC",
        "sync_now": "SYNC NOW",
        "last_sync": "Last sync",
        "syncing": "Syncing...",
        "sync_complete": "Sync complete",
        "sync_error": "Sync error",
        "unknown": "Unknown",
        "refresh": "REFRESH",
        "settings": "SETTINGS",
        "tools": "TOOLS",
        "view": "VIEW",
        "help": "HELP",
        "exit": "EXIT",
        "file": "File"
    },
    "ru": {
        "app_title": "WMR Group Apps",
        "welcome_title": "ДИСПЕТЧЕР ПРИЛОЖЕНИЙ WMR GROUP",
        "welcome_text": "СИСТЕМА РАСПРОСТРАНЕНИЯ И УПРАВЛЕНИЯ ПРИЛОЖЕНИЯМИ\n\nФУНКЦИИ:\n• Автоматическая проверка обновлений через GitHub API\n• Обнаружение EXE/BAT файлов в установленных приложениях\n• Централизованное управление приложениями\n• Контроль версий и уведомления об обновлениях\n• Простая установка и удаление\n\nВЫБЕРИТЕ ПРИЛОЖЕНИЕ В ЛЕВОЙ ПАНЕЛИ ДЛЯ ПРОСМОТРА ДЕТАЛЕЙ\nИ УПРАВЛЕНИЯ УСТАНОВКОЙ.",
        "available_apps": "ДОСТУПНЫЕ ПРИЛОЖЕНИЯ",
        "category_filter": "ФИЛЬТР КАТЕГОРИЙ:",
        "all": "ВСЕ",
        "flashing_tools": "ИНСТРУМЕНТЫ ПРОШИВКИ",
        "utilities": "УТИЛИТЫ",
        "installed": "УСТАНОВЛЕНО",
        "not_installed": "НЕ УСТАНОВЛЕНО",
        "check_updates": "ПРОВЕРИТЬ ОБНОВЛЕНИЯ",
        "open_install_folder": "ОТКРЫТЬ ПАПКУ УСТАНОВКИ",
        "open_install_directory": "ОТКРЫТЬ ДИРЕКТОРИЮ УСТАНОВКИ",
        "check_for_updates": "ПРОВЕРИТЬ ОБНОВЛЕНИЯ",
        "github": "GITHUB",
        "update_to": "ОБНОВИТЬ ДО",
        "uninstall": "УДАЛИТЬ",
        "detect_files": "ОБНАРУЖИТЬ ФАЙЛЫ",
        "detect_all_files": "ОБНАРУЖИТЬ ВСЕ ИСПОЛНЯЕМЫЕ ФАЙЛЫ",
        "install": "УСТАНОВИТЬ",
        "author": "АВТОР",
        "release_date": "ДАТА РЕЛИЗА",
        "github_stars": "ЗВЁЗДЫ НА GITHUB",
        "category": "КАТЕГОРИЯ",
        "install_path": "ПУТЬ УСТАНОВКИ",
        "status": "СТАТУС",
        "local_version": "ЛОКАЛЬНАЯ ВЕРСИЯ",
        "update_available": "ДОСТУПНО ОБНОВЛЕНИЕ",
        "detected_executable_files": "ОБНАРУЖЕННЫЕ ИСПОЛНЯЕМЫЕ ФАЙЛЫ",
        "no_files_detected": "ИСПОЛНЯЕМЫЕ ФАЙЛЫ НЕ ОБНАРУЖЕНЫ\n\nНажмите 'ОБНАРУЖИТЬ ФАЙЛЫ' для сканирования папки установки",
        "run": "ЗАПУСТИТЬ",
        "run_menu": "МЕНЮ ЗАПУСКА",
        "open_folder": "ОТКРЫТЬ ПАПКУ",
        "installing": "УСТАНОВКА",
        "preparing_download": "ПОДГОТОВКА К ЗАГРУЗКЕ...",
        "downloading_from_github": "ЗАГРУЗКА С GITHUB...",
        "extracting_files": "ИЗВЛЕЧЕНИЕ ФАЙЛОВ...",
        "copying_files": "КОПИРОВАНИЕ ФАЙЛОВ...",
        "creating_launchers": "СОЗДАНИЕ ЗАПУСКАЮЩИХ ФАЙЛОВ...",
        "finalizing": "ЗАВЕРШЕНИЕ...",
        "installation_complete": "УСТАНОВКА ЗАВЕРШЕНА!",
        "installation_failed": "ОШИБКА УСТАНОВКИ!",
        "view_error_details": "ПОСМОТРЕТЬ ДЕТАЛИ ОШИБКИ",
        "installation_error": "ОШИБКА УСТАНОВКИ",
        "close": "ЗАКРЫТЬ",
        "select_language": "Выберите язык",
        "english": "Английский",
        "russian": "Русский",
        "continue": "Продолжить",
        "updating": "ОБНОВЛЕНИЕ",
        "update_available_title": "Доступно обновление",
        "update_available_text": "Доступна новая версия {version}. Обновить сейчас?",
        "updating_app": "Обновление приложения...",
        "update_complete": "Обновление завершено!",
        "no_update": "Обновления не доступны",
        "error": "Ошибка",
        "success": "Успех",
        "info": "Информация",
        "warning": "Предупреждение",
        "yes": "ДА",
        "no": "НЕТ",
        "about": "О ПРОГРАММЕ",
        "about_program": "О ПРОГРАММЕ",
        "program_name": "WMR Group Apps",
        "version": "Версия",
        "developer": "Разработчик",
        "github_repo": "Репозиторий GitHub",
        "description": "Система распространения и управления приложениями для проектов WMR Group",
        "features": "Возможности",
        "feature1": "• Интеграция с GitHub и автоматические обновления",
        "feature2": "• Поддержка нескольких платформ (Windows, Linux, macOS)",
        "feature3": "• Многоязычный интерфейс (Английский, Русский)",
        "feature4": "• Централизованное управление приложениями",
        "feature5": "• Обнаружение и управление исполняемыми файлами",
        "license": "Лицензия",
        "mit_license": "Лицензия MIT",
        "loading": "Загрузка...",
        "please_wait": "Пожалуйста, подождите",
        "sync": "СИНХРОНИЗАЦИЯ",
        "sync_now": "СИНХРОНИЗИРОВАТЬ",
        "last_sync": "Последняя синхронизация",
        "syncing": "Синхронизация...",
        "sync_complete": "Синхронизация завершена",
        "sync_error": "Ошибка синхронизации",
        "unknown": "Неизвестно",
        "refresh": "ОБНОВИТЬ",
        "settings": "НАСТРОЙКИ",
        "tools": "ИНСТРУМЕНТЫ",
        "view": "ВИД",
        "help": "ПОМОЩЬ",
        "exit": "ВЫХОД",
        "file": "Файл"
    }
}